name: car_rental_a7md
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0-149.3.beta

  
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  cloud_firestore: ^5.3.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  lottie: ^3.1.2
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  uuid: ^4.5.0
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  location: ^6.0.2
  http: ^1.2.2
  shimmer: ^3.0.0
  intl: ^0.19.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding.png
    - assets/images/onboarding2.png
    - assets/images/user.png
    - assets/images/maps.png
    - assets/images/map.png    
    - assets/images/dev.jpg
    - assets/animations/loading.json
    - assets/animations/email.json
    - assets/animations/empty.json
    - assets/animations/refresh.json    
    - assets/icons/gear.svg
    - assets/icons/bell.svg
    - assets/icons/belll.svg
    
  
  fonts:
    - family: 'be'
      fonts:
        - asset: assets/fonts/2.TTF
    - family: 'ce'
      fonts:
        - asset: assets/fonts/3.ttf
