// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP8OEGz68NA3c_c5GMWmBN0ZWrfxiGrjU',
    appId: '1:384436575346:web:22b8d74faa7441af3636eb',
    messagingSenderId: '384436575346',
    projectId: 'car-rental-a7md-dc08d',
    authDomain: 'car-rental-a7md-dc08d.firebaseapp.com',
    databaseURL: 'https://car-rental-a7md-dc08d-default-rtdb.firebaseio.com',
    storageBucket: 'car-rental-a7md-dc08d.appspot.com',
    measurementId: 'G-P0RH1YE0G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD4AwA1NuUFLDkiLopEbSkIW4AKn0D53M',
    appId: '1:384436575346:android:046ab124341f10793636eb',
    messagingSenderId: '384436575346',
    projectId: 'car-rental-a7md-dc08d',
    databaseURL: 'https://car-rental-a7md-dc08d-default-rtdb.firebaseio.com',
    storageBucket: 'car-rental-a7md-dc08d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoqd56rYFtyxEakN66UVc1wUrBvH7Z6ow',
    appId: '1:384436575346:ios:40eec10c6726d8863636eb',
    messagingSenderId: '384436575346',
    projectId: 'car-rental-a7md-dc08d',
    databaseURL: 'https://car-rental-a7md-dc08d-default-rtdb.firebaseio.com',
    storageBucket: 'car-rental-a7md-dc08d.appspot.com',
    iosBundleId: 'com.example.carRentalA7md',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoqd56rYFtyxEakN66UVc1wUrBvH7Z6ow',
    appId: '1:384436575346:ios:40eec10c6726d8863636eb',
    messagingSenderId: '384436575346',
    projectId: 'car-rental-a7md-dc08d',
    databaseURL: 'https://car-rental-a7md-dc08d-default-rtdb.firebaseio.com',
    storageBucket: 'car-rental-a7md-dc08d.appspot.com',
    iosBundleId: 'com.example.carRentalA7md',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP8OEGz68NA3c_c5GMWmBN0ZWrfxiGrjU',
    appId: '1:384436575346:web:392f9d11a282cd843636eb',
    messagingSenderId: '384436575346',
    projectId: 'car-rental-a7md-dc08d',
    authDomain: 'car-rental-a7md-dc08d.firebaseapp.com',
    databaseURL: 'https://car-rental-a7md-dc08d-default-rtdb.firebaseio.com',
    storageBucket: 'car-rental-a7md-dc08d.appspot.com',
    measurementId: 'G-909K6TTG8F',
  );
}
